/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : LED_VERDE.h
**     Project     : EA076 - Projeto 1
**     Processor   : MKL25Z128VLK4
**     Component   : LED
**     Version     : Component 01.077, Driver 01.00, CPU db: 3.00.000
**     Compiler    : GNU C Compiler
**     Date/Time   : 2021-01-03, 16:59, # CodeGen: 5
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : LED_VERDE
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**            High Value means ON                          : no
**          Shell                                          : Disabled
**     Contents    :
**         On         - void LED_VERDE_On(void);
**         Off        - void LED_VERDE_Off(void);
**         Neg        - void LED_VERDE_Neg(void);
**         Get        - uint8_t LED_VERDE_Get(void);
**         Put        - void LED_VERDE_Put(uint8_t val);
**         SetRatio16 - void LED_VERDE_SetRatio16(uint16_t ratio);
**         Deinit     - void LED_VERDE_Deinit(void);
**         Init       - void LED_VERDE_Init(void);
**
**Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**All Rights Reserved.
**
**Redistribution and use in source and binary forms, with or without modification,
**are permitted provided that the following conditions are met:
**
**o Redistributions of source code must retain the above copyright notice, this list
**  of conditions and the following disclaimer.
**
**o Redistributions in binary form must reproduce the above copyright notice, this
**  list of conditions and the following disclaimer in the documentation and/or
**  other materials provided with the distribution.
**
**o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**  contributors may be used to endorse or promote products derived from this
**  software without specific prior written permission.
**
**THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**
**http: www.freescale.com
**mail: support@freescale.com
** ###################################################################*/
/*!
** @file LED_VERDE.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup LED_VERDE_module LED_VERDE module documentation
**  @{
*/         

#ifndef __LED_VERDE_H
#define __LED_VERDE_H

/* MODULE LED_VERDE. */
#include "MCUC1.h" /* SDK and API used */
#include "LED_VERDEconfig.h" /* LED configuration */
#include "LEDpin2.h" /* interface to pin */

#define LED_VERDE_ClrVal()    LEDpin2_ClrVal() /* put the pin on low level */
#define LED_VERDE_SetVal()    LEDpin2_SetVal() /* put the pin on high level */
#define LED_VERDE_SetInput()  LEDpin2_SetInput() /* use the pin as input pin */
#define LED_VERDE_SetOutput() LEDpin2_SetOutput() /* use the pin as output pin */

#define LED_VERDE_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#if LED_VERDE_CONFIG_IS_LOW_ACTIVE
  #define LED_VERDE_On() LEDpin2_ClrVal()
#else
  #define LED_VERDE_On() LEDpin2_SetVal()
#endif
/*
** ===================================================================
**     Method      :  LED_VERDE_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#if LED_VERDE_CONFIG_IS_LOW_ACTIVE
  #define LED_VERDE_Off() LEDpin2_SetVal()
#else
  #define LED_VERDE_Off() LEDpin2_ClrVal()
#endif
/*
** ===================================================================
**     Method      :  LED_VERDE_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_VERDE_Neg() LEDpin2_NegVal()
/*
** ===================================================================
**     Method      :  LED_VERDE_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#if LED_VERDE_CONFIG_IS_LOW_ACTIVE
  #define LED_VERDE_Get() (!(LEDpin2_GetVal()))
#else
  #define LED_VERDE_Get() LEDpin2_GetVal()
#endif
/*
** ===================================================================
**     Method      :  LED_VERDE_Get (component LED)
**     Description :
**         This returns logical 1 in case the LED is on, 0 otherwise.
**     Parameters  : None
**     Returns     :
**         ---             - Status of the LED (on or off)
** ===================================================================
*/

void LED_VERDE_Init(void);
/*
** ===================================================================
**     Method      :  LED_VERDE_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LED_VERDE_Put(val)  ((val) ? LED_VERDE_On() : LED_VERDE_Off())
/*
** ===================================================================
**     Method      :  LED_VERDE_Put (component LED)
**     Description :
**         Turns the LED on or off.
**     Parameters  :
**         NAME            - DESCRIPTION
**         val             - value to define if the LED has to be on or
**                           off.
**     Returns     : Nothing
** ===================================================================
*/

void LED_VERDE_Deinit(void);
/*
** ===================================================================
**     Method      :  LED_VERDE_Deinit (component LED)
**     Description :
**         Deinitializes the driver
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void LED_VERDE_SetRatio16(uint16_t ratio);
/*
** ===================================================================
**     Method      :  LED_VERDE_SetRatio16 (component LED)
**     Description :
**         Method to specify the duty cycle. If using a PWM pin, this
**         means the duty cycle is set. For On/off pins, values smaller
**         0x7FFF means off, while values greater means on.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ratio           - Ratio value, where 0 means 'off' and
**                           0xffff means 'on'
**     Returns     : Nothing
** ===================================================================
*/

/* END LED_VERDE. */

#endif
/* ifndef __LED_VERDE_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
